config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  devise_for :users
  resources :courses do
    resources :lessons
  end

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  get "/up/", to: "up#index", as: :up
  get "admin" => "admin#index"
  get "/up/databases", to: "up#databases", as: :up_databases

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html

  root "courses#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100,100]
  end
  has_many :lessons
  has_and_belongs_to_many :categories

  def first_lesson
    self.lessons.order(:position).first
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_one_attached :video
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show update ]

  # GET /lessons/1 or /lessons/1.json
  def show
    @course = @lesson.course
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :paid, :course_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/up_controller.rb
class UpController < ApplicationController
  def index
    head :ok
  end

  def databases
    RedisConn.current.ping
    ActiveRecord::Base.connection.execute("SELECT 1")

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/index.html.erb
<h1>Index Admin Page</h1>

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>" class="max-w-sm rounded-b overflow-hidden shadow-lg hover:bg-cyan-100">
  <%= link_to course, class: "flex flex-col h-full" do %>
    <% if course.image.present? %>
      <%= image_tag course.image, class: "w-full rounded-t " %>
    <% else %>
      <%= image_tag("https://via.placeholder.com/300") %>
    <% end %>

    <div class="px-6 py-4 flex flex-col justify-between grow">
      <div>
        <div class="flex items-center justify-between font-bold text-xl mb-2">
          <%= course.title %>
        </div>

        <p class="text-sm font-extralight">Some Name</p>

        <div>
          <p class="text-md font-light">Free</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/_sidebar.html.erb
<div class="flex flex-col lg:pl-6">
  <div class="mt-6 lg:mt-0 flex justify-center items-center w-full">
    <div class="bg-white rounded-lg shadow-lg overflow-hidden w-full">
      <div class="bg-red-500 p-4">
        <h2 class="text-gray-50 text-2xl font-bold">Start Learning</h2>
      </div>

      <div class="p-4">
        <% if user_signed_in? %>
          <p class="text-gray-700 text-base mb-4">
            Start the course and begin learning all about the world of web dev.
          </p>
          <%= link_to "Start Course", course_lesson_path(@course, @course.first_lesson), class: "bg-violet-600 hover:bg-violet-700 text-gray-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
        <% else %>
          <p class="text-gray-700 text-base mb-4">
            Sign up for free today and start exploring the endless possibilities.
          </p>
          <%= link_to "Sign Up", new_user_registration_path, class: "bg-violet-600 hover:bg-violet-700 text-gray-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
        <% end %>
      </div>

      <% if @course.paid %>
        <div class="mt-6 flex justify-center items-center w-full">
          <div class="bg-white rounded-lg shadow-lg overflow-hidden w-full">
            <div class="p-4 bg-red-500">
              <h2 class="text-gray-50 text-2xl font-bold">Get More Content</h2>
            </div>

            <div class="p-4">
              <% if user_signed_in? %>
                <p class="text-gray-700 text-base mb-4">
                  Unlock more content by purchasing the full course
                </p>
                <button class="bg-violet-600 hover:bg-violet-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150">Unlock full course</button>
              <% else %>
                <p class="text-gray-700 text-base mb-4">
                  Sign up for free today
                </p>
                <%= link_to "Sign Up", new_user_registration_path, class: "bg-violet-600 hover:bg-violet-700 text-gray-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block py-2 px-3"><%= notice %></p>
  <% end %>

  <h1>Courses</h1>

  <div id="courses" class="min-w-full flex flex-wrap justify-center gap-14 pb-6">
    <%= render @courses %>
  </div>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<div class="mx-auto w-full flex flex-col lg:flex-row pb-6">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="px-3 py-2 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
        <%= notice %>
      </p>
    <% end %>

    <% if @course.lessons.any? && @course.lessons.first.video.present? %>
      <%= video_tag @course.lessons.first.video, controls: true, class: "w-full rounded mb-6" %>
    <% end %>

    <div class="border p-6 rounded">
      <div class="flex justify-start items-center flex-wrap w-full mb-2">
        <% @course.categories.each do |category| %>
          <div class="bg-amber-100 text-amber-800 text-sm font-semibold mt-2 mr-2 px-2.5 py-0.5 rounded">
            <%= category.name %>
          </div>
        <% end %>
      </div>

      <span><%= @course.lessons.count %> <%= "lesson".pluralize(@course.lessons.count) %></span>

      <h1 class="text-2xl font-bold"><%= @course.title %></h1>
      <p class="text-gray-500 mt-2"><%= @course.description %></p>
    </div>

    <div>
      <%= render "sidebar" %>
    </div>

    <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Docker + Rails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A production ready example Rails app that's using Docker and Docker Compose.">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# Generated with: https://realfavicongenerator.net/ %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body class="flex flex-col h-screen justify-between">
    <div class="bg-gray-700">
      <div class="max-w-screen-lg mx-auto py-3 px-3 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between flex-wrap">
          <div class="flex-1 flex items-center">
            <span class="flex p-2 rounded-lg bg-gray-900">
              <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            </span>
            <p class="ml-3 font-medium text-white truncate">
              Rails <%= Rails::VERSION::STRING %> and Ruby <%= ENV["RUBY_VERSION"] %>
            </p>
          </div>
          <div class="mt-2 order-3 w-full sm:mt-0 sm:w-auto">
            <div class="rounded-md shadow-sm">
              <span class="flex items-center justify-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-gray-500">
                RAILS_ENV = <%= Rails.env %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <main class="max-w-screen-lg mx-auto mb-auto">
      <%= yield %>
    </main>

    <footer class="text-center mt-6 pb-6 h-10">
      <p class="text-gray-500">
        <a class="border-b mb-1" href="https://github.com/nickjj/docker-rails-example">Coded</a>
        with
        <svg class="h-5 w-5 text-red-600 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
        </svg>
        by
        <a class="border-b mb-1" href="https://nickjanetakis.com">Nick Janetakis</a>
      </p>
    </footer>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :paid, style: "display: block" %>
    <%= form.check_box :paid %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Title:</strong>
    <%= lesson.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= lesson.description %>
  </p>

  <p>
    <strong>Paid:</strong>
    <%= lesson.paid %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= lesson.course_id %>
  </p>

</div>

app/views/lessons/_sidebar.html.erb
<div class="w-full">
  <% course.lessons.order(:position).each do |lesson| %>
    <% if lesson.paid %>
    <div class="border p-6 hover:bg-gray-200">
      <div>
        <%= icon('fa-solid', 'lock', class: "mr-2 text-gray-600") %>
        <span class="font-light"><%= lesson.title %></span>
      </div>
    </div>
    <% else %>
      <%= link_to course_lesson_path(course, lesson) do %>
        <div class="border p-6 hover:bg-gray-200 <%= @lesson.id == lesson.id ? 'bg-red-100' : '' %>">
          <span class="font-light"><%= lesson.title %></span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lessons</h1>

<div id="lessons">
  <% @lessons.each do |lesson| %>
    <%= render lesson %>
    <p>
      <%= link_to "Show this lesson", lesson %>
    </p>
  <% end %>
</div>

<%= link_to "New lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/show.html.erb
<div class="mx-auto w-full flex flex-col lg:flex-row pb-6">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="px-3 py-2 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
        <%= notice %>
      </p>
    <% end %>

    <%= (@lesson.video.present?) ? (video_tag @lesson.video, autoplay: false, controls: true, class: "rounded") : "No video available" %>

    <div class="my-2 border p-4 rounded">
      <h1 class="text-2xl font-semibold">
        <%= @lesson.title %>
      </h1>
      <p class="text-gray-700"><%= @lesson.description %></p>
    </div>

    <div class="my-6 lg:mb-0">
      <%= link_to "Mark as complete", course_lesson_path(@course, @lesson), data: { 'turbo-method' => :put }, class: "bg-green-500 rounded hover:bg-green-600 text-white px-4 py-2" %>
    </div>
  </div>

  <div class="sidebar_container lg:min-w-60 lg:mr-4 lg:overflow-y-scroll">
    <%= render "sidebar", course: @course %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="flex justify-center pt-24 pb-12 px-2 sm:px-0">
  <%= image_tag "ruby-on-rails.png", size: "480x188", alt: "Rails logo" %>
</div>

<p class="text-center text-lg">
 🐳 Learn the Docker fundamentals at:
  <strong>
    <a class="border-b border-gray-900 mb-1" href="https://diveintodocker.com?ref=docker-rails-example">https://diveintodocker.com</a>
  </strong>
</p>